service: crud-serverless-users

plugins:
  - serverless-offline
  - serverless-dynamodb-local

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: arn:aws:dynamodb:us-east-1:133052086422:table/usersTable

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: false
      migrate: true
      # noStart: true  

functions:
  get-users:
    handler: getUsers/handler.getUsers
    events:
      - http:
          path: users/{id}
          method: GET
  create-users:
    handler: createUsers/handler.createUsers
    events:
      - http:
          path: users
          method: POST
  update-users:
    handler: updateUsers/handler.updateUsers
    events:
      - http:
          path: users/{id}
          method: PATCH
  delete-users:
    handler: deleteUsers/handler.deleteUsers
    runtime: python3.8
    events:
      - http:
          path: users/{id}
          method: DELETE

package:
  individually: true
  patterns:
    - "!.dynamodb"
    - "!.node_modules"

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1